#include "test.h"
#include <libyuc/container/hash_list.h>
#include <libyuc/space_manager/buddy.h>

#include <libyuc/object.c>


LIBYUC_SPACE_MANAGER_BUDDY_DEFINE(, int32_t, LIBYUC_SPACE_MANAGER_BUDDY_4BIT_INDEXER, LIBYUC_OBJECT_ALLOCATOR_DEFALUT)


//typedef struct _IntLru_Entry {
//	IntHashListEntry lru_entry;
//	int key;
//} IntLru_Entry;
//#define IntLruListEntryAccessor_GetKey(LRU_LIST, LRU_LIST_ENTRY) (&((IntLru_Entry*)(LRU_LIST_ENTRY))->key)
//#define IntLruListEntryAccessor IntLruListEntryAccessor
//LIBYUC_CONTAINER_LRU_LIST_DEFINE(Int, int, IntLruListEntryAccessor, LIBYUC_OBJECT_ALLOCATOR_DEFALUT, LIBYUC_OBJECT_HASHER_DEFALUT, LIBYUC_OBJECT_COMPARER_DEFALUT)


#define TEST_COMPARER_DEFALUT_Equal(MAIN_OBJ, OBJ1, OBJ2) (memcmp((OBJ1), (OBJ2), 16) == 0)
#define TEST_COMPARER_DEFALUT_Greater(MAIN_OBJ, OBJ1, OBJ2) (memcmp((OBJ1), (OBJ2), 16) > 0)
#define TEST_COMPARER_DEFALUT_Less(MAIN_OBJ, OBJ1, OBJ2) (memcmp((OBJ1), (OBJ2), 16) < 0)
#define TEST_COMPARER_DEFALUT_Subrrac(MAIN_OBJ, OBJ1, OBJ2) (memcmp((OBJ1), (OBJ2), 16))
#define TEST_COMPARER_DEFALUT TEST_COMPARER_DEFALUT
    LIBYUC_CONTAINER_RB_TREE_DEFINE(Int, IntRbEntry*, int64_t, INT_RB_TREE_REFERENCER, INT_RB_TREE_ACCESSOR, TEST_COMPARER_DEFALUT)

    //LIBYUC_CONTAINER_AVL_TREE_DEFINE(Int, IntAvlEntry*, int, INT_AVL_TREE_REFERENCER, INT_AVL_TREE_ACCESSOR, LIBYUC_OBJECT_COMPARER_DEFALUT)




LIBYUC_CONTAINER_HASH_TABLE_DEFINE(Int, int64_t, int64_t, LIBYUC_OBJECT_ALLOCATOR_DEFALUT, INT_HASHTABLE_ACCESSOR, LIBYUC_OBJECT_MOVER_DEFALUT, INT_HASHTABLE_HASHER_KEY, LIBYUC_OBJECT_COMPARER_DEFALUT)



    LIBYUC_SPACE_MANAGER_BUDDY_DECLARATION(Element, int16_t)
    LIBYUC_SPACE_MANAGER_BUDDY_DEFINE(Element, int16_t, LIBYUC_SPACE_MANAGER_BUDDY_4BIT_INDEXER, LIBYUC_OBJECT_ALLOCATOR_DEFALUT)

